const USER = ["view_user", "add_user", "delete_user", "change_user"]


// ["add_group",
// "change_group",
// "delete_group"]
// "view_group",
// "add_measurement",
// "change_measurement",
// "delete_measurement",
// "view_measurement",
// "add_measurementtype",
// "change_measurementtype",
// "delete_measurementtype",
// "view_measurementtype",
// "add_ngo",
// "change_ngo",
// "delete_ngo",
// "view_ngo",
// "add_ngoregistrationresource",
// "change_ngoregistrationresource",
// "delete_ngoregistrationresource",
// "view_ngoregistrationresource",
// "add_resource",
// "change_resource",
// "delete_resource",
// "view_resource",
// "add_user",
// "bos_admin",
// "change_user",
// "delete_user",
// "view_user",
// "add_userhierarchy",
// "change_userhierarchy",
// "delete_userhierarchy",
// "view_userhierarchy",
// "add_userreading",
// "change_userreading",
// "delete_userreading",
// "view_userreading",
// "add_userresource",
// "change_userresource",
// "delete_userresource",
// "view_userresource"

export { USER };
